dist: xenial
language: bash
sudo: true

branches:
  only: master

notifications:
  email: false

git:
  depth: 5

addons:
  apt:
    packages:
      - autoconf
      - automake
      - autopoint
      - build-essential
      - libtool
      - pkg-config
      - bison
      - flex
      - make
      - gcc
      - git
      - gawk
      - gettext
      - texinfo
      - patch
      - libgmp3-dev
      - libltdl-dev
      - libmpc-dev
      - libmpfr-dev
      - zlib1g-dev
      - bzip2
      - xz-utils
      - cpio
      - kmod
      - automake1.11

env:
  global:
    - TZ: "Asia/Taipei"
    - secure: "oEF0UWiJESmBi8UpBP97hNaqegbMFq6BMhTvxW4eR3wCK9Ymzsq6+oep7vAQXA4yx8BZPVJ5wA+1GBBg7LGTFpgUknx+xbcWM4GvQZWn7J+92vIhznTVraXLF1Sandk6EeRM2DpYlZAwL5qoqArqGwmnwPIfDtIUbXEE/6m1/edAiJI678hdUuJ06TcUa2d3hswlMjwMGi6p0YKJzS/5h09WM13PbLT4rvuiZizstXldsBjiZ1ZPRZZsVZyvQGvUiNJx/KcPnyA6x3j8tbqJbEEMfuwMSUkwYKhBd1LWpASAc9qeeoeiKy2HU4PCTD2NcW+8fZnntMwQVdkgJCcECsWG6RF11ixa2hAKchPdR0bvM6/p9PkLFiIoi4MEWHFW7CUp5v2p1AzPrvSvircypPfhi1E04laUduV8qANnW1CsrXiwnYURLKTwsHoMhunXj7QX/NQcLuXXmrg8/3Gj3olXGiSUQys44bk2f3aC2n8lLGuTKICQPAwQ1JUMzHvcbGshoqyxXWI+CQjOIJXpN0eMMg2/pYPBJlDHeaOkqmkNRKmGsphzPRTJ3s7SOlK0ZLnnt+EhPr7oEntdEPC6cJe3lcZtzEzvrtZwNf/EIb6kc6lZBVNrVrwiBjM9OyDr0Ju6Rc4H5ZSwxEl9HE8sfpRWCIFrBp29kkJmPAsntpg="

script:
  - travis_wait 30 sleep infinity &
  - ./build.sh MI-MINI &> /dev/null

after_success:
  - ./deploy.sh
