name: CI

on:
  push:
    branches: master
  release:
    types: published
  workflow_dispatch:

env:
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: pexcn/docker-images:buster-padavan
      options: --user builder
    strategy:
      matrix:
        TARGET:
          - "MI-MINI"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: ./build.sh ${{ matrix.TARGET }}
      - name: Upload to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.TARGET }}
          path: trunk/images/*.trx
